### ISSUE TITLE
http dial timeout can be too short

### ISSUE THREAD

**Issue by cspargo** [jacksontj/promxy#104] opened 2018-12-15 21:02 UTC
I have some prometheus instances that are about 200ms away. Since the dial timeout is hard coded to 200ms, i intermittently get connection failures. I understand that the httpclient config options are from the prometheus library, so difficult to alter, but would it perhaps be possible to add a global level config setting to override the dial timeout?

**Comment by jacksontj** [comment] 2018-12-17 18:39
Thanks for the report! Basically this is a dupe of #72. I attempted getting a change in upstream, but it has been ~3 months, so at this point I've just added the feature in promxy itself (#105). It will still default to 200ms, but it is configurable per-severgroup.

**Closed** 2018-12-17 18:40 UTC
Labels: duplicate, enhancement
