### ISSUE TITLE
remote_read not working

### ISSUE THREAD

**Issue by samsk** [jacksontj/promxy#262] opened 2020-02-08 07:40 UTC
I believe remote_read is not working, and promxy always uses query API instead. I've tried version 0.0.56, 0.0.57 and also git head, with same results.

My config:
```
    - static_configs:
        - targets:
#            - 10.252.64.2:9090
            - 10.252.64.3:9090
      labels:
        mon_id: ''
      anti_affinity: 10s
      remote_read: true
```

in tcpdump i see
```
....
POST /api/v1/query HTTP/1.1
Host: 10.252.64.3:9090
User-Agent: Go-http-client/1.1
Content-Length: 47
Content-Type: application/x-www-form-urlencoded

query=up%7Bmon%3D%22x%22%7D&time=1581147336.745
```

**Comment by samsk** [comment] 2020-02-15 23:37
I've had time to debug this. This bug was introduced in commit e8df3111aef6bd9431e9806ef95037e04c0bc3b5, that modified file pkg/proxystorage/proxy.go .
After reverting the commit, the test query (query=up) goes to remote read api.

**Comment by jacksontj** [comment] 2020-02-18 21:49
This is actually a somewhat intended behavior -- albeit a confusing one. TLDR; its how its supposed to work (for performance reasons).

Longer explanation:

The main performance bottleneck in promxy/prometheus is the number of datapoints we have to ship around on the wire. The remote_read API returns the raw points for a series. So for example, if I wanted to know a value every hour for a day the `query_range` API would respond with 24 points, whereas the remote_read API would return with every scrape point within that 24h window. This commit was put in with the express purpose of shoving as much data as possible over the query_range API where we can reduce the data that we need to ship across the wire. So if you were to do a `sum(irate(foo[1m]))` before and after that change it would *also* not use remote_read. So in reality the `remote_read` option is only when we have to fall back to fetching data directly (e.g. MatrixSelectors).


So with all of that said, is this causing issues for you? Or just an unexpected change? This was a significant performance improvement -- so I don't plan on removing it. Depending on the use-case we could make this configurable, but given that this is the case for most aggregations etc. that seems like it wouldn't be worth much (meaning if you don't support query_range, promxy already doesn't really work).

**Comment by samsk** [comment] 2020-02-19 08:53
Ok, I understand now, thanks for the explanation. This should be maybe better explained in the documentation, also with remark that Query API is faster (?) and therefore preferred (?).

This behavior is not working in my (wanted) setup. I'm using [postgresql-prometheus-adapter](https://github.com/timescale/prometheus-postgresql-adapter) with postgresql and timescale extension for long-term metrics storage, and this adapter provides only Read API, not Query API.
I wanted to point promxy directly to prometheus-postgresql-adapter, joined with multiple prometheus instances that I have, but this is not working as expected. So for now I'm staying with having remote_read configured in prometheus(es) and, the prometheus queries the postgresql over pure remote Read API. But this is an extra data round-trip, that puts additional load on prometheus(es).

It would be great if promxy could handle this without the need of prometheus as middle-man, but this might be a bigger change, because only reverting that commit fixes only query=up, but other type of queries still seem to go via Query API sometimes.

**Comment by jacksontj** [comment] 2020-02-19 16:32
> also with remark that Query API is faster (?) and therefore preferred (?).

The query API is significantly faster for the cases it is required (vector selectors, aggregates, etc.) -- which is why it doesn't even allow for the remote_read option there. When we are fetching the "raw" data (MatrixSelector such as `foo[1h]`) remote_read is somewhat faster and does allow prometheus to ship StaleNans (covered in the docs).

> I wanted to point promxy directly to prometheus-postgresql-adapter,

Yea, unfortunately this isn't supported today. We could add some support in for that but the perf impact to the promxy nodes would be significant (as it'd spend a lot of time with marshaling etc.). TBH I'd suggest actually looking into adding promql (prom API) support to that postgres adapter. Once you have the storage adapter the rest is just wiring up the HTTP endpoint.

> But this is an extra data round-trip, that puts additional load on prometheus(es).

A thought here, you can configure a separate prometheus with no scraping and just the remote-read API to not add the additional load to the scraping prometheus hosts.

**Comment by samsk** [comment] 2020-02-19 16:42
Yes, I was also thinking about adding proxy prometheus, that will do the remote_read proxying ;-) That will be temporary solution, and later I'll maybe explore how to extend prometheus adapter.

Thanks for your help.

**Comment by jacksontj** [comment] 2020-02-19 16:45
When you get around to extending that adapter, you can just take a look at how I'm wiring up the promql engine:

- https://github.com/jacksontj/promxy/blob/master/acmd/promxy/main.go#L189
- https://github.com/jacksontj/promxy/blob/master/acmd/promxy/main.go#L189


Or if you don't need as much customization you could take a look at how prometheus itself does it (https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L359)


Always glad to be of help! I'll go ahead and close this out then and merge in that docs clarification :)

**Closed by jacksontj** 2020-02-19 16:45 UTC
Labels: question
