### ISSUE TITLE
Whole group is down if one of targets is down

### ISSUE THREAD

**Issue by hasso** [jacksontj/promxy#156] opened 2019-06-04 08:22 UTC
I have a group with two static targets and if one of these is down promxy gets 502 from it (response from proxy). It worked fine, but since 0.0.34 it doesn't any more – if one of targets is down, promxy also returns an error.

**Comment by jacksontj** [comment] 2019-06-04 17:53
This is actually a dupe of #153 -- this is actually the expected behavior, which was broken before (in 0.0.31) and fixed in https://github.com/jacksontj/promxy/commit/608375b938102a4d05f26f93f12b1e0e904fbad0 (0.0.34). In that same release I added an `ignore_error` option (https://github.com/jacksontj/promxy/blob/master/servergroup/config.go#L94) which enables you to have the previous behavior.

Keep in mind though that if you go to this previous behavior if 1 shard of data (meaning all that unique data) is unavailable queries will continue to succeed. A simple example would be 2 shards of unique data and getting the summed QPS across them. If 1 shard were to fail the QPS would half -- but you'd get no error. The behavior by default is to require at least 1 node from each "shard" of data to respond, since we won't know at query time whether it has data we need to answer the query or not.

Hopefully that clarifies the situation some, as always if you have any questions definitely let me know.

**Comment by jacksontj** [comment] 2019-06-06 05:40
@hasso did that clear it up? If so I'll go ahead and close this issue out, if not hopefully I can be of assistance :)

**Comment by jacksontj** [comment] 2019-06-07 03:29
I'm going to go ahead and close this out, if you have any further questions please feel free to re-open.

**Closed by jacksontj** 2019-06-07 03:29 UTC

**Comment by hasso** [comment] 2019-06-07 09:00
OK. I think that I understand the reasons behind the change, but two comments. `ignore_error` will work for my use case for now, but it would be nice to have it documented somehow :). And I really think that the correct way to solve this is make promxy aware which targets contain duplicate data and which not.

**Comment by jacksontj** [comment] 2019-06-07 14:37
Ignore error has some documentation [here](https://github.com/jacksontj/promxy/blob/master/servergroup/config.go#L98) but I can see how that isn't sufficient. I have opened #165 to add clarification to that docstring (if thats still unclear let me know :) ).

As for a more-correct way of solving this, I agree that promxy knowing which targets contain duplicate data would be significantly better. At a high-level this effectively ends up being the same issue as #2  (where we don't have a mechanism to know what all metrics each prometheus has). As it stands today promxy will route the query to all servers that *might* have data for the result. Meaning if your query's matchers *don't* match a servergroup (based on the labels promxy would add) then we won't route the query there. If you have any other feedback on that problem feel free to chime in, at this point the best mechanism I can think of is some attempted bloom-filter implementation based on what we see as "unique" labels (which would be eventually-consistent, but is probably "okay").
