### ISSUE TITLE
query for series doesn't take date range into account

### ISSUE THREAD

**Issue by allesplawik** [jacksontj/promxy#505] opened 2022-03-10 14:15 UTC
So far, the query has returned all data from the entire range using the start and end parameters, but now the query for the labels from all ranges doesn't return all data, ex. query

`curl -X GET -s https://xxx/api/v1/series\?match%5B%5D\=kafka_streams_thread_commit_total%7Bthread_id\=%22oralloy_event_raw_v2%22%7D\&start\=1646481620\&end\=1646917620 | jq '.data | length'
17`

`curl -X GET -s https://xxx/api/v1/series\?match%5B%5D\=kafka_streams_thread_commit_total%7Bthread_id\=%22oralloy_event_raw_v2%22%7D\&start\=1646482620\&end\=1646917620 | jq '.data | length'
17`

`curl -X GET -s https://xxx/api/v1/series\?match%5B%5D\=kafka_streams_thread_commit_total%7Bthread_id\=%22oralloy_event_raw_v2%22%7D\&start\=1646483620\&end\=1646917620 | jq '.data | length'
17`
 
`curl -X GET -s https://xxx/api/v1/series\?match%5B%5D\=kafka_streams_thread_commit_total%7Bthread_id\=%22oralloy_event_raw_v2%22%7D\&start\=1646484620\&end\=1646917620 | jq '.data | length'
17`

As you can see, changing the start parameter doesn't work. It looks like promxy return data from the end of the range. 
Only the change of the end value causes the change of the list of returned series.

**Comment by jacksontj** [comment] 2022-07-31 05:00
As I was unable to reproduce this issue (and there haven't been other reports) I'm going to go ahead and close this out. If you can still reproduce this error please feel free to re-open so we can continue debugging!

**Closed by jacksontj** 2022-07-31 05:00 UTC
Labels: question
