### ISSUE TITLE
Inconsistency response data for aggregation sum(rate) query

### ISSUE THREAD

**Issue by dezenxi** [jacksontj/promxy#592] opened 2023-04-21 04:42 UTC
Hi,

We have 2 identical Prometheus servers running on the same namespace for High Availability. 
We tried to test promxy for High Availability by restarting one of Prometheus servers.
However, promxy sometimes returns aggregation query data which looks abnormal 
when one of Prometheus servers restarting.
Query:  sum(rate(prometheus_http_requests_total{kubernetes_pod_name=~"promxy.*"}[1m]))&start=1681897209.108&end=1681899009.108&step=15

The sequence of test is as below:
-  Restart Prometheus server called pod0, in the pictures pod0 restarted around 2023-04-19T10:09:12.741Z
-  Send query range to promxy after pod0 restarting sum(rate(prometheus_http_requests_total{kubernetes_pod_name=~"promxy.*"}[1m]))&start=1681897209.108&end=1681899009.108&step=15
-  Check graph of promxy, Prometheus server pod0, and Prometheus server pod1

It was found that sometimes graph of promxy was same with restarting pod, Prometheus server pod0
 <img width="751" alt="promxy_230419_100924_gh" src="https://user-images.githubusercontent.com/10127665/233542162-7b2f46f2-8e4f-4316-b538-f2ce012ba94f.png">

Graph of Prometheus server pod0, there is a dip down around restarting timestamp.
<img width="741" alt="pod0_230419_100920_gh" src="https://user-images.githubusercontent.com/10127665/233542255-3611e763-26b4-44fd-8666-73812e0fe6ba.png">

Graph of Prometheus server pod1, the sum(rate) return looks normal
<img width="747" alt="pod1_230419_100920_gh" src="https://user-images.githubusercontent.com/10127665/233542331-83392f51-53dc-447a-8434-a44cc5fee45b.png">

In this case, we expected promxy would not accept or merge pod0 data around its restating time, 2023-04-19T10:09:12. However,  promxy merge and response data from Prometheus server pod0 although pod0 rate calculation was not correct as missing some data points.

I found out that there is similar issue https://github.com/jacksontj/promxy/issues/311
It seems was fixed for parser.SubqueryExpr, how about parser.AggregateExpr (sum(rate)) ?
Could you please check if this is a bug, is it possible fix this issue?

Regards,
Duong

**Comment by jacksontj** [comment] 2023-04-21 05:10
First off, thanks for reaching out! Always great to see people using this project! So lets dig in a bit:


> In this case, we expected promxy would not accept or merge pod0 data around its restating time,

This is actually a bit of a tricky one to explain -- but I'll give it a shot. Promxy doesn't know that your downstream restarted -- the only way it knows to "merge" data is when there is a hole in the data large enough that it decides its a hole that needs filling (this "hole" is determined by the [anti_affinity](https://github.com/jacksontj/promxy/blob/master/pkg/servergroup/config.go#L141).

> However, promxy merge and response data from Prometheus server pod0 although pod0 rate calculation was not correct as missing some data points.

So based on the context above -- promxy only knows about the "hole" if there is an actual hole in the data. Now if you were looking at `prometheus_http_requests_total` directly -- there is probably a hole (and it probably stitches together more-or-less correctly). This is because the query from the downstream has a hole. Now your actual query ` sum(rate(prometheus_http_requests_total{kubernetes_pod_name=~"promxy.*"}[1m]))` sends a different query downstream. It will (basically) send that same query to both downstreams and merge the results. Now prometheus/promql has some interesting behaviors with a few functions (and rate specifically) where it seems to just fill in the holes (you can mess with this with a combination of "lookback delta" and the duration in the matrixselector -- the 1m in this case).

So in more simple terms, if you ran that same sum query against the source (as it seems you did in the screenshots) there isn't a hole in the data (just a weird spike to 0). So unfortunately promxy just sees a series with a 0 in the middle -- which is a valid value and so it doesn't identify a hole and then doesn't "merge" the data (since it sees no hole).


So with that I'm not sure of a much better way to handle this other than experimenting with the [LookbackDelta](https://github.com/prometheus/prometheus/blob/main/cmd/prometheus/main.go#L398) (which is 5m by default) on the downstream promethues boxes (to get it to return an actual hole). I've kicked around ideas of some "smarter" merge logic -- but the issue is there isn't a really general/repeatable way to know which series is 'correct' (in this case "bigger is better" -- but that may be exactly wrong for some other query). 


Hopefully that provides some context as to the behavior you are seeing -- as always suggestions/PRs are welcome!

**Comment by dezenxi** [comment] 2023-04-24 04:55
Hi,

I've tried to test by adjusting LookbackDelta value (0s, or 30s), but it does not help.
Promxy still fetched response data from restarting pod.

Graph of promxy (lookbackdelta = 0s) after restarting pod0
<img width="831" alt="promxy_230424_042532_gh" src="https://user-images.githubusercontent.com/10127665/233901534-bf2d468b-0109-48ea-b8c1-35dcec18bd4b.png">

Graph of pod0
<img width="836" alt="pod0_230424_042532_gh" src="https://user-images.githubusercontent.com/10127665/233901951-a7f189c2-fe1a-40e3-a6f2-c8504442d3e3.png">

Graph of pod1

<img width="821" alt="pod1_230424_042532_gh" src="https://user-images.githubusercontent.com/10127665/233902866-26532eab-b8b3-42b9-bade-94b679ce2ccb.png">

I'm finding another alternatives, I appreciate if you have another suggestions. 

Regards,
Duong

**Comment by jacksontj** [comment] 2023-04-30 20:38
My apologies; it seems I was unclear. I was referring to changing the LookbackDelta on the downstream prometheus nodes (the option is available in both promxy and prometheus).

Since the prometheus node is the one returning the weird dip (instead of a hole) it is the one that we'd want to modify the lookback delta (so it instead returns a hole).

**Comment by dezenxi** [comment] 2023-05-04 04:41
Hi @jacksontj ,

#LookbackDelta on the downstream prometheus nodes (the option is available in both promxy and prometheus).
Yes. I tried to change LookbackDelta on downstream node, and the result was as in 
https://github.com/jacksontj/promxy/issues/592#issuecomment-1519380483
Seems changing LookbackDelta would not take affect on rate() function of prometheus.

Regards,
Duong

**Comment by jacksontj** [comment] 2023-05-05 23:30
So I spent some time messing around with this and the only way I can reproduce this sort of issue is if the downstream prometheus is sending odd data. Could you provide the `trace` log output from promxy when you run the above queries? That'll include the data that downstream returned -- so we can investigate further.

**Comment by dezenxi** [comment] 2023-05-12 09:01
Hi @jacksontj 

I tried to reproduce the issue.
Sequence of event happened as following:

1/ Restarting pod0 at Thu, 11 May 2023 11:41:55
>Start Time:       Thu, 11 May 2023 11:41:55 +0200
The pod0 was up/running after ~40s

2/ After pod0 was up, sent a query-range to promxy "2023-05-11T09:43:06Z"
>time="2023-05-11T09:43:06Z" level=debug msg="AggregateExpr sum(rate(prometheus_http_requests_total{kubernetes_pod_name=~\".*promxy.*\"}[1m])) sum"

3/ Check the graph of promxy, pod0, pod1 around 11:41:55 ~ 11:42:06
Promxy graph 
<img width="867" alt="promxy_230511_094201" src="https://github.com/jacksontj/promxy/assets/10127665/cf1b6b18-877b-4dce-9af3-84019f32cb5e">


pod0 graph/
<img width="859" alt="pod0_230511_094201" src="https://github.com/jacksontj/promxy/assets/10127665/6b78aaba-83de-4919-a2b4-e75bd5c5765c">

pod1 graph/
<img width="849" alt="pod1_230511_094201" src="https://github.com/jacksontj/promxy/assets/10127665/f3cc578f-c9bd-40d9-a974-07311524f83d">

You can see the graph of promxy was same with pod0 around 11:41:55 ~ 11:42:06

4/ I tried to get promxy log at trace level around the time
[promxy_log_gh_230511.txt](https://github.com/jacksontj/promxy/files/11461277/promxy_log_gh_230511.txt)

>pod0: 0.39999999999999997 @[1683798096.673]\n0.42219407595049224 @[1683798111.673]\n0.3028143993688679 @[1683798126.673]\n0.42223160514678104 @[1683798141.673]\n0.40003555871633034 @[1683798156.673]\n0.3205133333333333 @[1683798171.673]\n0.39999999999999997 @[1683798186.673]" warnings="[]"

> pod1: 0.39999999999999997 @[1683798096.673]\n0.42222222222222217 @[1683798111.673]\n0.42222222222222217 @[1683798126.673]\n0.42222222222222217 @[1683798141.673]\n0.39999999999999997 @[1683798156.673]\n0.39999999999999997 @[1683798171.673]\n0.39999999999999997 @[1683798186.673]" warnings="[]"

According to promxy graph, we can see promxy pick value from pod0 at 1683798126,  1683798156...
The expectation is that promxy should pick value from pod1 at mentioned timestamp

Regards,
Duong

**Comment by dezenxi** [comment] 2023-05-29 02:08
Hi @jacksontj ,

Do you have any update from my latest reproduction logs?

Thanks,
Duong

**Comment by garyclee** [comment] 2023-05-31 07:01
Hi @jacksontj

I've tried to address the dips here:

https://github.com/jacksontj/promxy/compare/master...garyclee:promxy:mergemax

I understand bigger isn't always suitable, but it seems to address this issue in most cases. It also optional, defaults to disabled.

What do you think?

Thanks
Gary

**Comment by jacksontj** [comment] 2023-06-02 22:33
So I did some looking on the data you provided (thanks for that!).

Within that dataset three is a 120s gap of data on pm-server-1 (from 1683797586.673 -> 1683797796.673).

To more easily showcase the issue I put this data in a [google sheet](https://docs.google.com/spreadsheets/d/1n0ssAe-cna7ElktzLSQfvgkefT98_wLR1Rq6Lc06EEo/edit#gid=0). But I'll also include some screenshots here.

![Screenshot from 2023-06-02 15-23-39](https://github.com/jacksontj/promxy/assets/1619869/9e479042-7b6b-4b6a-bd10-b5e67248dc89)

So to summarize what happened here:
- promxy got 2 series back -- one with a hole in it
- promxy selected the series with more points (and in this case, with no hole)
- promxy returns the value from server-0 -- as it has no holes (so no need to merge)

In this case, server-0 (for some reason) has some weird spikes near the end; but that is not due to merging logic from promxy (as that was the data returned from the downstream API). So (un)fortunately it seems that promxy did what it was supposed to do and it returned the series without a hole (as a matter-of-fact, no "merge" required!). I would also expect that if you sent the same query repeatedly you should get the same result (meaning the result from promxy is "stable").

Hopefully that clears it up some? In this case it seems promxy did "the right thing" so not much to do, unless I'm missing something?

**Comment by dezenxi** [comment] 2023-06-03 02:38
Hi @jacksontj ,
Thanks for checking the logs,
> Within that dataset three is a 120s gap of data on pm-server-1 (from 1683797586.673 -> 1683797796.673).
Yes. This is expected gap, as I scaled prometheus from 2 pods to 1-pod.  The pod1 was scaled-down more than 3 mins. Then,  rate[1m] of pod1 would return nothing. It is actually a hole.  Promxy could detect the hole aroun 1683797586.673 -> 1683797796.673. It picked pod0 values as expected. Thanks. :)

The next question is why promxy could not pick correct value at 1683798126 when pod0 was restarting within 40s.
I guess the rate[1m] still returns value (extrapolate?) although pod0 was missing some data points in 40s of restarting.
pod0: 0.3028143993688679 @[1683798126.673]
pod1: 0.42222222222222217 @[1683798126.673]

Do you have any ideas to help promxy to pick the correct value at 1683798126 ? 
Or Promxy just simply pick from list longer returned series ? 

Regards,
Duong

**Comment by jacksontj** [comment] 2023-06-07 05:14
> The next question is why promxy could not pick correct value at 1683798126 when pod0 was restarting within 40s.

The problem here is that promxy has no idea that any pod has restarted. Since the downstream API is returning data promxy has to merge based on what it sees.

>  Or Promxy just simply pick from list longer returned series ?

The merge logic will take base off of the largest series; then fill any holes within a series (based on the antiAffinity configuration)

**Comment by garyclee** [comment] 2023-06-07 06:08
Hi @jacksontj 

Not sure if you saw https://github.com/jacksontj/promxy/issues/592#issuecomment-1569605819

Should I send a PR?

VictoriaMetrics seems to do a similar thing, but on the raw data.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#deduplication

**Comment by dezenxi** [comment] 2023-06-28 02:04
Hi @jacksontj  ,
As @garyclee e investigation, seems VictoriaMetrics prefer to max/larger values when both downstream return values.
Is it feasible to add new option to allow user make a choice as [PR 600](https://github.com/jacksontj/promxy/pull/600) ?

Thanks
Duong

**Comment by jacksontj** [comment] 2023-08-23 04:29
Merged https://github.com/jacksontj/promxy/pull/600 :)

**Closed by jacksontj** 2023-08-23 04:29 UTC
Labels: question
