### ISSUE TITLE
内置的Prometheus版本太低，部分查询语法不支持

### ISSUE THREAD

**Issue by bbaobelief** [jacksontj/promxy#608] opened 2023-07-25 03:53 UTC
通过promxy查询报错
```
**Error executing query: found duplicate series for the match group {k8s_cluster="xxx-prod"} on the right hand-side of the operation:;many-to-many matching not allowed: matching labels must be unique on one side**
```
同样的语句在Prometheus=2.35.0版本查询就没问题。

**Comment by jacksontj** [comment] 2023-07-27 03:49
Thanks for reporting the issue, could you please provide some additional information on how to reproduce this bug? Ideally a query against a public prometheus endpoint (for easy repro).

**Comment by jacksontj** [comment] 2023-08-10 05:15
Since there hasn't been a response in a couple of weeks I'm going to go ahead and close this issue out (as there isn't enough detail to debug further). If you want to resume looking into this issue please provide some additional data and we can re-open this and continue investigating.

**Closed by jacksontj** 2023-08-10 05:15 UTC
