### ISSUE TITLE
Comparing to remote_read

### ISSUE THREAD

**Issue by Wing924** [jacksontj/promxy#22] opened 2018-04-25 00:07 UTC
Hello!
Currently, I use prometheus remote_read to archive:

* no more "holes" in metrics
* single source in grafana
* no need for aggregation layers of prometheus anymore!

*I konw this function is not designed for this purpose, but it works.*

My config is like:
```yml
remote_read:
- url: http://prom-us1:9090/api/v1/read
- url: http://prom-us2:9090/api/v1/read
- url: http://prom-jp1:9090/api/v1/read
- url: http://prom-jp2:9090/api/v1/read
```
I found remote_read  is faster than promxy with some queries.
For example, simple query like `cpu_usage{hostname="myserver"}`, remote_read is fater than promxy. But aggregated query like `count(up{})`,  promxy is fater than remote_read.

I think it's needed to add a document to compare and benchmark remote_read and promxy.

**Comment by jacksontj** [comment] 2018-04-25 00:41
The reason for this (at least in my benchmarking) is actually due to the serial performance of prometheus itself. Promxy uses the `/v1` promql HTTP API for most queries. The data resulting there is actually returned as JSON and depending on the **size** of that response the perf might be really bad (https://github.com/prometheus/prometheus/issues/3601).

Could you provide the outputs of those queries and maybe an example dataset to reproduce with? My expectation is that this is largely due to marshaling limitations on the prometheus side, but I'd like to verify :)

**Comment by jacksontj** [comment] 2018-04-25 00:44
oh, and how could I forget-- promxy also supports using the `remote_read` API if you set [this option ](https://github.com/jacksontj/promxy/blob/master/servergroup/config.go#L33) to `true`. Once that api is no longer "experimental" then I'll likely change the default.

**Comment by Wing924** [comment] 2018-04-25 01:57
After I changed to remote_read, it becomes much faster 😀

**Comment by jacksontj** [comment] 2018-04-25 02:02
FYI in prometheus 2.2 they upgraded the JSON marshaler to `json_iter` which is on-par performance-wise with the `remote_read` API.

**Comment by jacksontj** [comment] 2018-04-26 04:07
I've added a note in the README about this. I'll go ahead and close this issue out, if you run into any other issues definitely let me know!

**Closed by jacksontj** 2018-04-26 04:07 UTC

**Comment by Wing924** [comment] 2018-04-26 05:15
@jacksontj 
I'm using prometheus 2.2.1 now. I'm not sure why, but `remote_read: true` is around 20% faster than `remote_read: false`. Maybe JSON vs protocol buffers?

**Comment by jacksontj** [comment] 2018-04-27 04:11
That's my expectation.
