### ISSUE TITLE
prometheus query broken..

### ISSUE THREAD

**Issue by ThomasADavis** [jacksontj/promxy#228] opened 2019-10-22 04:39 UTC
something broke between 0.48 and 0.53..

this query:

GET /api/v1/query HTTP/1.1 200 117" 0.010227 query=min%28elasticsearch_cluster_health_status%7Bcolor%3D%22green%22%7D%29%2B%28min%28elasticsearch_cluster_health_status%7Bcolor%3D%22yellow%22%7D%29%2A2%29&time=1571719003

stopped returning any data using 0.53, and works fine with 0.48.  it doesn't matter if it's prometheus or victoriametrics that is the data source.  switching away from promxy directly to the prometheus/victoriametrics datasource and it works fine.

**Comment by jacksontj** [comment] 2019-10-22 05:55
@ThomasADavis do you have the response from promxy with that query? (the response should include the error, or traceback) which will help with debugging.

**Comment by ThomasADavis** [comment] 2019-10-22 22:02
This is what grafana reports with 0.48

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/55/api/v1/query?query=min(elasticsearch_cluster_health_status%7Bcolor%3D%22green%22%7D)%2B(min(elasticsearch_cluster_health_status%7Bcolor%3D%22yellow%22%7D)*2)&time=1571777683"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {},
          "value": [
            1571777683,
            "1"
          ]
        }
      ]
    }
  }
}
```
debug level:

```192.168.85.157 - - [22/Oct/2019 21:55:09] "GET /api/v1/query HTTP/1.1 200 116" 0.005082 query=min%28elasticsearch_cluster_health_status%7Bcolor%3D%22green%22%7D%29%2B%28min%28elasticsearch_cluster_health_status%7Bcolor%3D%22yellow%22%7D%29%2A2%29&time=1571781310
DEBU[2019-10-22T14:55:39-07:00] AggregateExpr min(elasticsearch_cluster_health_status{color="green"}) 
DEBU[2019-10-22T14:55:39-07:00] AggregateExpr min(elasticsearch_cluster_health_status{color="yellow"}) 
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" ts="2019-10-22 14:55:40 -0700 PDT"
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" ts="2019-10-22 14:55:40 -0700 PDT"
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" ts="2019-10-22 14:55:40 -0700 PDT"
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" ts="2019-10-22 14:55:40 -0700 PDT"
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" took=3.513578ms ts="2019-10-22 14:55:40 -0700 PDT"
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" took=3.332281ms ts="2019-10-22 14:55:40 -0700 PDT"
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" took=5.276466ms ts="2019-10-22 14:55:40 -0700 PDT"
DEBU[2019-10-22T14:55:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" took=5.203358ms ts="2019-10-22 14:55:40 -0700 PDT"
192.168.85.157 - - [22/Oct/2019 21:55:39] "GET /api/v1/query HTTP/1.1 200 117" 0.006873 query=min%28elasticsearch_cluster_health_status%7Bcolor%3D%22green%22%7D%29%2B%28min%28elasticsearch_cluster_health_status%7Bcolor%3D%22yellow%22%7D%29%2A2%29&time=1571781340
DEBU[2019-10-22T14:56:09-07:00] AggregateExpr min(elasticsearch_cluster_health_status{color="green"}) 
DEBU[2019-10-22T14:56:09-07:00] AggregateExpr min(elasticsearch_cluster_health_status{color="yellow"}) 
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" ts="2019-10-22 14:56:10 -0700 PDT"
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" ts="2019-10-22 14:56:10 -0700 PDT"
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" ts="2019-10-22 14:56:10 -0700 PDT"
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" ts="2019-10-22 14:56:10 -0700 PDT"
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" took=3.376877ms ts="2019-10-22 14:56:10 -0700 PDT"
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" took=3.602097ms ts="2019-10-22 14:56:10 -0700 PDT"
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" took=3.418047ms ts="2019-10-22 14:56:10 -0700 PDT"
DEBU[2019-10-22T14:56:09-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" took=3.398723ms ts="2019-10-22 14:56:10 -0700 PDT"
192.168.85.157 - - [22/Oct/2019 21:56:09] "GET /api/v1/query HTTP/1.1 200 116" 0.004899 query=min%28elasticsearch_cluster_health_status%7Bcolor%3D%22green%22%7D%29%2B%28min%28elasticsearch_cluster_health_status%7Bcolor%3D%22yellow%22%7D%29%2A2%29&time=1571781370
```

and with 0.53:

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/55/api/v1/query?query=min(elasticsearch_cluster_health_status%7Bcolor%3D%22green%22%7D)%2B(min(elasticsearch_cluster_health_status%7Bcolor%3D%22yellow%22%7D)*2)&time=1571777620"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": []
    }
  }
}
```

debug:

```
DEBU[2019-10-22T14:59:39-07:00] AggregateExpr min(elasticsearch_cluster_health_status{color="green"}) 
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" ts="2019-10-22 14:59:40 -0700 PDT"
DEBU[2019-10-22T14:59:39-07:00] AggregateExpr min(elasticsearch_cluster_health_status{color="yellow"}) 
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" ts="2019-10-22 14:59:40 -0700 PDT"
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" ts="2019-10-22 14:59:40 -0700 PDT"
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" ts="2019-10-22 14:59:40 -0700 PDT"
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" took=2.439035ms ts="2019-10-22 14:59:40 -0700 PDT"
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-1:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" took=2.078243ms ts="2019-10-22 14:59:40 -0700 PDT"
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"green\"})" took=4.066867ms ts="2019-10-22 14:59:40 -0700 PDT"
DEBU[2019-10-22T14:59:39-07:00] http://dae-vmetric-2:8428                     api=Query query="min(elasticsearch_cluster_health_status{color=\"yellow\"})" took=3.620974ms ts="2019-10-22 14:59:40 -0700 PDT"
192.168.85.157 - - [22/Oct/2019 21:59:39] "GET /api/v1/query HTTP/1.1 200 87" 0.006323 query=min%28elasticsearch_cluster_health_status%7Bcolor%3D%22green%22%7D%29%2B%28min%28elasticsearch_cluster_health_status%7Bcolor%3D%22yellow%22%7D%29%2A2%29&time=1571781580
```

**Comment by jacksontj** [comment] 2019-11-07 03:43
First off, my apologies for the delay in getting back -- its a very busy time of year :)

So, I have spent a bunch of time this evening attempting to reproduce this issue and am unable to do so -- to be fair I don't have the API responses etc. so I'm not certain my repro case is the same.

I tried to repro using `min(prometheus_http_request_duration_seconds_count{handler="/"}) + (min(prometheus_http_request_duration_seconds_count{handler="/metrics"}) *2)` (I also tried generating some fake data with real values as well as NaNs. The only way I was able to get that behavior was if I set the LookbackDelta to something *very* short (e.g. `--query.lookback-delta=1s`)-- which I imagine isn't the case you are seeing.

So I think to get this we'll need the `trace` level logs and/or a pcap of the traffic -- that way I can see what is exactly being put on the wire (either way will get me the info I need).

**Comment by gseddon** [comment] 2019-11-10 05:32
I have encountered the same issue. Here is an example request:
`ifInPkts{device_id="9951",group="bond0",parent_group="interface"}`
Below is the trace level logs from promxy 0.48, where the result renders just fine
```
time="2019-11-10T05:22:39Z" level=debug msg="http://nsda3bpldv51.aa.dynamic.in.telstra.com.au:8428" api=QueryRange query="ifInPkts{device_id=\"9951\",group=\"bond0\",parent_group=\"interface\"}" r="{2019-11-10 05:02:39.321 +0000 UTC 2019-11-10 05:22:39.321 +0000 UTC 3s}"
time="2019-11-10T05:22:39Z" level=trace msg="http://nsda3bpldv51.aa.dynamic.in.telstra.com.au:8428" api=QueryRange error="<nil>" query="ifInPkts{device_id=\"9951\",group=\"bond0\",parent_group=\"interface\"}" r="{2019-11-10 05:02:39.321 +0000 UTC 2019-11-10 05:22:39.321 +0000 UTC 3s}" took=95.157872ms value="ifInPkts{db=\"irrelevant\", device_id=\"9951\", group=\"bond0\", parent_group=\"interface\", sg=\"victoria_metrics\"} =>\n114467396458 @[1573362159]\n114467396458 @[1573362162]\n114467396458 @[1573362165]\n114467396458 @[1573362168]\n114467396458 @[1573362171]\n114467396458 @[1573362174]\n114467396458 @[1573362177]\n114467396458 @[1573362180]\n114467396458 @[1573362183]\n114467396458 @[1573362186]\n114467396458 @[1573362189]\n114467396458 @[1573362192]\n114467396458 @[1573362195]\n114467396458 @[1573362198]\n114467396458 @[1573362201]\n114467396458
....
@[1573363359]\n114469165857 @[1573363362]" warnings="[]"
```
And below is the log from promxy 0.53, which gives me the error "no datapoints found" 
```
time="2019-11-10T05:24:50Z" level=debug msg="http://testing-victoria-metrics.threshold.svc.cluster.prod:8428" api=QueryRange query="ifInPkts{device_id=\"9951\",group=\"bond0\",parent_group=\"interface\"}" r="{2019-11-10 05:09:50.204 +0000 UTC 2019-11-10 05:24:50.204 +0000 UTC 3s}"
time="2019-11-10T05:24:50Z" level=trace msg="http://testing-victoria-metrics.threshold.svc.cluster.prod:8428" api=QueryRange error="<nil>" query="ifInPkts{device_id=\"9951\",group=\"bond0\",parent_group=\"interface\"}" r="{2019-11-10 05:09:50.204 +0000 UTC 2019-11-10 05:24:50.204 +0000 UTC 3s}" took=42.652841ms value="ifInPkts{db=\"irrelevant\", device_id=\"9951\", group=\"bond0\", parent_group=\"interface\"} =>\n114467838214 @[1573362588]\n114467838214 @[1573362591]\n114467838214 @[1573362594]\n114467838214 @[1573362597]\n114468281870 @[1573362600]\n114468281870 @[1573362603]\n114468281870 @[1573362606]\n114468281870 @[1573362609]\n114468281870 @[1573362612]\n114468281870 @[1573362615]\n114468281870 @[1573362618]\n114468281870 @[1573362621]\n114468281870 @[1573362624]\n114468281870 @[1573362627]\n114468281870 @[1573362630]\n114468281870 @[1573362633]\n114468281870 @[1573362636]\n114468281870 @[1573362639]\n114468281870 @[1573362642]\n114468281870 @[1573362645]\n114468281870 @[1573362648]\n114468281870 @[1573362651]\n114468281870 @[1573362654]\n114468281870 @[1573362657]\n114468281870 @[1573362660]\n114468281870 
...
@[1573363485]\n114469165857 @[1573363488]\n114469165857 @[1573363491]" warnings="[]"
```
I have trimmed some extra numbers where the (...) are.

**Comment by jacksontj** [comment] 2019-11-25 21:00
I attempted to reproduce this and was unable. The 2 things I can think of either (1) this is an issue with `nocache` not being set (https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml#L50) or (2) the query_range includes all mutable time in VM which is subject to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/241

**Comment by ThomasADavis** [comment] 2019-11-25 21:39
Interesting - in reading that, by changing the grafana query time shift field to anything greater than 15 seconds, it works.

I do have the nocache=1 setting in the promxy config.

**Comment by jacksontj** [comment] 2019-11-25 21:44
Then that sounds like the same upstream VM bug (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/241) is the cause of this issue as well.

The `nocache=1` is being passed, its just that VM seems to be ignoring it for the most recent time window.

**Comment by jacksontj** [comment] 2019-11-27 02:33
Upstream has fixed the code, I'm going to close this issue out as it should be resolved :)

**Closed by jacksontj** 2019-11-27 02:33 UTC
