### ISSUE TITLE
relabel_configs doesn't do relabeling

### ISSUE THREAD

**Issue by codedumper1** [jacksontj/promxy#495] opened 2022-02-03 19:35 UTC
My metrics look like this:
> metricA{host="ip-172-16-25-14.eu-west-2.compute.internal", input="cloudwatch", sg="promxy"}
> metricA{host="ip-172-16-25-15.eu-west-2.compute.internal", input="cloudwatch", sg="promxy"}

What I intend to do is to get rid of 2nd duplicate metric which comes through different telegraf output, but since _host_ is registered it appears to be different hence not deduplicated.

Problem I have is that I need to relabel _host_ **only** if another label _input_ is set to "cloudwatch". Therefore my relabel_configs looks like this:
```
relabel_configs:
   - source_labels: [input]
     regex: "cloudwatch"
     target_label: host
     replacement: "telegraf"
```
As written in https://github.com/jacksontj/promxy/issues/260, relabel_configs should be in the server_group section in promxy. However this doesn't work. My full promxy config looks like this:
```
global:
  scrape_interval: 10s
  external_labels:
    source: vm

promxy:
  server_groups:
    - static_configs:
        - targets:
            - 172.16.1.1:8428
            - 172.16.2.1:8428
      labels:
        sg: promxy
      anti_affinity: 10s
      remote_read: false
      query_params:
        nocache: 1
      scheme: http
      http_client:
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
      ignore_error: true

      relabel_configs:
        - source_labels: [input]
          regex: "cloudwatch"
          target_label: host
          replacement: "telegraf"
```
I tried to make sense of relabel_configs vs metric_relabel_configs from https://github.com/jacksontj/promxy/issues/136, but still no luck. What is wrong? Can function I need be implemented?

**Comment by jacksontj** [comment] 2022-07-31 05:06
`relabel_configs` is a bit confusing in that it actually applies to the labels of the targets within a servergroup (more details in https://github.com/jacksontj/promxy/pull/89). So this won't help with re-labeling the metrics coming *from* a target.

So this *seems* to be effectively a duplicate of https://github.com/jacksontj/promxy/issues/258 -- requesting the ability to dedupe across other labels.

**Comment by jacksontj** [comment] 2022-11-21 20:30
Closing as a dupe of #258

**Closed by jacksontj** 2022-11-21 20:30 UTC
Labels: duplicate, question
