### ISSUE TITLE
Promxy fails to query any metrics when one of many ServerGroups has no available targets

### ISSUE THREAD

**Issue by nfrush** [jacksontj/promxy#153] opened 2019-05-23 15:38 UTC
When Promxy has a group of two or more targets and all of the targets go down in that group, this inhibits ANY group from being queried (regardless of their status). I'll add a reproducible example later(and attempt a PR).

**Comment by jacksontj** [comment] 2019-05-23 15:57
This is actually intended behavior. Promxy has no concept of what metrics are in which shards, so the expectation is that each servergroup needs to respond with something. If you wish to make a specific servergroup optional you can do so with the `ignore_error` option (https://github.com/jacksontj/promxy/blob/master/servergroup/config.go#L94)

**Comment by jacksontj** [comment] 2019-05-25 17:07
@nfrush were you able to create an example config to repro?

**Comment by jacksontj** [comment] 2019-06-03 17:49
@nfrush I'm going to go ahead and close this out -- but feel free to re-open if you have an example case. I did some testing myself last week and was unable to come up with a config where this wasn't expected (maybe not documented well enough? but at least expected). If you have an example config I'd be glad to clarify if that was expected or not, and if its still confusing we can definitely update comments etc. to clarify.

**Closed by jacksontj** 2019-06-03 17:49 UTC
