### ISSUE TITLE
help, how to drop 'prometheus' label on different servergroup?

### ISSUE THREAD

**Issue by gotosre** [jacksontj/promxy#534] opened 2023-01-29 04:51 UTC
help, how to drop 'prometheus' label on different servergroup?

**Comment by gotosre** [comment] 2023-01-29 04:53
desc:
two ups:
- thanos with label prometheus: thanos
- victoriametrics with label prometheus: vm

promxy in front of them to uniform entry

how to remove prometheus label ,when query via promxy? any config?

**Comment by jacksontj** [comment] 2023-03-09 22:44
This appears to be a duplicate of #258 ?

**Closed** 2023-03-14 23:32 UTC
Labels: duplicate
