### ISSUE TITLE
Browser access returns the following, why？and How do we get him to return correctly

### ISSUE THREAD

**Issue by mzk1234567-mzk** [jacksontj/promxy#578] opened 2023-03-24 08:06 UTC
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/68324917/227460778-21d38809-1076-420c-bdd1-71c68b8f23b2.png">

**Comment by mzk1234567-mzk** [comment] 2023-03-24 08:15
![image](https://user-images.githubusercontent.com/68324917/227462817-33e16c1e-b016-4993-a061-391ed0b027cb.png)

**Comment by jacksontj** [comment] 2023-03-24 17:05
Hmm, I haven't seen this issue in a long time -- are you running on `latest`? or some older version? Also -- what platform are you running on? (I have tested on linux amd64, armv7, and arm64 personally specifically on the UI)

**Comment by pyfdtic** [comment] 2023-04-03 04:11
i meet this error last week, and add tag `-tags netgo,builtinassets` may fix the error

**Comment by jacksontj** [comment] 2023-04-03 04:14
Those flags are included in the official releases (both the [docker containers](https://github.com/jacksontj/promxy/blob/04b3ea999c324381dde95210341f920e9f6fabbb/Dockerfile#L9) and the [binaries that are published](https://github.com/jacksontj/promxy/blob/b8f56ba6cc093160e34b41dbe67a17e4f299119b/build.bash#L35)).

I tested this on a few machines and am unable to reproduce this on latest (after the most recent prom upgrade). Note: this was a known issue for arm prior to that update.

**Comment by jacksontj** [comment] 2023-04-16 04:22
Its been a while with no update so I'm going to go ahead and close this out (assuming this issue is resolved). If you are still seeing this issue please re-open this and we can continue debugging :)

**Closed by jacksontj** 2023-04-16 04:22 UTC
